services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 todo_app.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa@2025#

volumes:
  postgres_data: